In [1]:
print('Machine Learning Soil Fertility prediction ')

Machine Learning Soil Fertility prediction

In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns
import statsmodels.api as sm

In [3]:
data = pd.read_excel('Data_new_latih.xlsx')
data_test=pd.read_excel('Data_new_uji.xlsx')

In [4]:
df1 = pd.DataFrame(data_test)
selected_columns = ['Impedance']  # Kolom yang ingin diambil
Predict_Sample = df1[selected_columns]
Predict_Sample

    Impedance
0      102.13
1       93.17
2       71.51
3       74.49
4       87.17
5       55.41
6       82.63
7       79.35
8       87.52
9       58.32
10      90.90
11      83.11
12      33.20
13      35.90

In [5]:
Data_Koreksi=pd.read_excel('Data_new_koreksi.xlsx')

In [6]:
columns_to_drop = ['Sample_Code','Impedance']  # Ganti dengan nama kolom yang ingin dihapus

Koreksi_Model = Data_Koreksi.drop(columns=columns_to_drop)
Koreksi_Model

,Mg,Al,Si,Fe,S,Cl,K,Ca,Ti,Zn,...,Ni,Ga,Ta,V,Cr,Mn,C,P,N,pH
0,3.34,21.98,56.91,12.99,0.07,0.08,0.67,0.00,3.43,0.01,...,0.01,0.01,0.00,0.08,0.04,0.02,0.19,0.001206,0.050,4.75
1,3.09,18.95,60.17,12.71,0.12,0.08,0.71,0.12,3.49,0.01,...,0.01,0.01,0.00,0.08,0.05,0.03,2.14,0.002510,0.090,5.13
2,2.85,19.31,65.63,8.35,0.11,0.10,0.47,0.00,0.00,0.01,...,0.01,0.00,0.00,0.06,0.03,0.01,0.19,0.000956,0.050,4.80
3,1.05,20.49,66.33,8.35,0.11,0.09,0.47,0.06,2.67,0.01,...,0.01,0.01,0.00,0.06,0.03,0.01,2.53,0.000408,0.040,4.78
4,2.77,22.44,58.49,12.37,0.07,0.08,0.44,0.00,2.86,0.01,...,0.01,0.00,0.02,0.07,0.04,0.01,0.19,0.000257,0.060,4.87
5,4.14,24.97,52.61,13.07,0.03,0.02,0.41,1.34,2.94,0.01,...,0.01,0.01,0.02,0.08,0.02,0.03,2.53,0.002243,0.050,7.34
6,4.30,20.52,59.62,11.26,0.08,0.06,0.58,0.04,3.09,0.01,...,0.00,0.01,0.00,0.07,0.04,0.01,2.40,0.001934,0.080,4.90
7,5.72,21.82,54.45,13.43,0.05,0.05,0.61,0.00,3.37,0.01,...,0.00,0.01,0.02,0.08,0.04,0.02,1.13,0.000480,0.058,4.80
8,4.35,16.08,67.22,8.16,0.09,0.06,0.46,0.36,2.75,0.01,...,0.01,0.00,0.02,0.06,0.05,0.02,3.23,0.016089,0.120,5.08
9,4.35,20.30,62.16,9.19,0.08,0.07,0.43,0.13,2.84,0.01,...,0.01,0.01,0.02,0.07,0.05,0.01,1.90,0.001296,0.050,5.01
10,4.08,19.23,61.15,11.71,0.11,0.08,0.43,0.04,2.72,0.01,...,0.01,0.00,0.02,0.06,0.03,0.02,3.40,0.001025,0.110,4.93
11,5.65,20.59,58.05,12.03,0.07,0.06,0.42,0.00,2.67,0.01,...,0.01,0.01,0.02,0.06,0.03,0.01,2.56,0.000492,0.060,4.96
12,3.08,22.08,57.21,12.25,0.08,0.03,0.61,1.35,0.00,0.02,...,0.01,0.00,0.02,0.07,0.05,0.05,2.14,0.004275,0.080,6.80
13,3.46,23.34,54.73,13.60,0.05,0.03,0.41,0.91,2.98,0.01,...,0.01,0.01,0.02,0.09,0.03,0.02,2.10,0.001377,0.146,6.56

In [7]:
Pelatihan=pd.read_excel('Pelatihan_new.xlsx')

In [8]:
df123 = pd.DataFrame(Pelatihan)
selected_columns = ['Impedance']  # Kolom yang ingin diambil
x_p = df123[selected_columns]

columns_to_drop = ['Sample_Code', 'Impedance']  # Ganti dengan nama kolom yang ingin dihapus

y_p = Pelatihan.drop(columns=columns_to_drop)

In [9]:
from sklearn.model_selection import train_test_split
xp_train,xp_test,yp_train,yp_test=train_test_split(x_p,y_p,test_size=0.30,random_state=0)

In [10]:
from sklearn.tree import DecisionTreeRegressor
Dc = DecisionTreeRegressor(max_depth=30, random_state=30) 
Dc.fit(xp_train, yp_train)
Result_predictions_D30 = Dc.predict(Predict_Sample)
print(Result_predictions_D30)

[[3.950e+00 2.179e+01 6.729e+01 5.903e+01 7.000e-02 7.000e-02 4.400e-01
  1.000e-02 2.680e+00 1.000e-02 3.000e-01 1.000e-02 1.000e-02 0.000e+00
  5.000e-02 4.000e-02 1.000e-02 1.560e+00 5.960e-04 7.000e-02 5.090e+00]
 [3.090e+00 1.895e+01 6.017e+01 1.271e+01 1.200e-01 8.000e-02 7.100e-01
  1.200e-01 3.490e+00 1.000e-02 3.600e-01 1.000e-02 1.000e-02 0.000e+00
  8.000e-02 5.000e-02 3.000e-02 2.140e+00 2.510e-03 9.000e-02 5.130e+00]
 [2.850e+00 1.931e+01 6.563e+01 8.350e+00 1.100e-01 1.000e-01 4.700e-01
  0.000e+00 0.000e+00 1.000e-02 2.900e-01 1.000e-02 0.000e+00 0.000e+00
  6.000e-02 3.000e-02 1.000e-02 1.900e-01 9.560e-04 5.000e-02 4.800e+00]
 [1.050e+00 2.049e+01 6.633e+01 8.350e+00 1.100e-01 9.000e-02 4.700e-01
  6.000e-02 2.670e+00 1.000e-02 2.500e-01 1.000e-02 1.000e-02 0.000e+00
  6.000e-02 3.000e-02 1.000e-02 2.530e+00 4.080e-04 4.000e-02 4.780e+00]
 [2.750e+00 2.243e+01 5.848e+01 1.235e+01 7.000e-02 8.000e-02 4.200e-01
  0.000e+00 2.860e+00 1.000e-02 3.100e-01 1.000e-02 0.000e+00 2.000e-02
  7.000e-02 4.000e-02 1.000e-02 1.900e-01 2.530e-04 6.000e-02 4.820e+00]
 [4.130e+00 2.494e+01 5.263e+01 1.367e+01 3.000e-02 2.000e-02 4.200e-01
  1.340e+00 2.937e+00 1.000e-02 2.500e-01 1.000e-02 1.000e-02 2.000e-02
  8.100e-02 2.000e-02 3.000e-02 2.530e+00 2.242e-03 5.000e-02 7.320e+00]
 [5.610e+00 2.059e+01 5.805e+01 1.203e+01 7.000e-02 6.000e-02 4.200e-01
  0.000e+00 2.670e+00 1.000e-02 3.000e-01 1.000e-02 1.000e-02 2.000e-02
  6.000e-02 3.000e-02 1.000e-02 2.560e+00 4.920e-04 6.000e-02 4.960e+00]
 [5.710e+00 2.184e+01 5.442e+01 1.341e+01 5.000e-02 5.000e-02 6.400e-01
  0.000e+00 3.450e+00 1.000e-02 3.700e-01 0.000e+00 1.000e-02 2.000e-02
  8.200e-02 4.200e-02 2.000e-02 1.140e+00 4.500e-04 5.600e-02 4.770e+00]
 [4.320e+00 1.610e+01 6.726e+01 8.145e+00 9.000e-02 6.200e-02 4.400e-01
  3.500e-01 2.740e+00 1.000e-02 2.700e-01 1.000e-02 0.000e+00 2.000e-02
  6.500e-02 5.000e-02 2.000e-02 3.200e+00 1.580e-02 1.190e-01 5.010e+00]
 [4.350e+00 2.030e+01 6.216e+01 9.190e+00 8.000e-02 7.000e-02 4.300e-01
  1.300e-01 2.840e+00 1.000e-02 2.900e-01 1.000e-02 1.000e-02 2.000e-02
  7.000e-02 5.000e-02 1.000e-02 1.900e+00 1.296e-03 5.000e-02 5.010e+00]
 [4.050e+00 1.925e+01 6.112e+01 1.169e+01 1.200e-01 8.000e-02 4.200e-01
  4.300e-02 2.700e+00 1.000e-02 3.090e-01 1.000e-02 0.000e+00 2.000e-02
  6.200e-02 3.000e-02 2.000e-02 3.440e+00 1.000e-03 1.090e-01 4.910e+00]
 [5.610e+00 2.059e+01 5.805e+01 1.203e+01 7.000e-02 6.000e-02 4.200e-01
  0.000e+00 2.670e+00 1.000e-02 3.000e-01 1.000e-02 1.000e-02 2.000e-02
  6.000e-02 3.000e-02 1.000e-02 2.560e+00 4.920e-04 6.000e-02 4.960e+00]
 [3.080e+00 2.210e+01 5.724e+01 1.221e+01 8.000e-02 3.000e-02 6.300e-01
  1.320e+00 0.000e+00 2.000e-02 2.400e-01 1.000e-02 0.000e+00 2.000e-02
  7.000e-02 5.000e-02 5.000e-02 2.130e+00 4.100e-03 8.000e-02 6.700e+00]
 [3.820e+00 2.110e+01 5.816e+01 1.151e+01 1.000e-01 2.000e-02 6.000e-01
  1.370e+00 2.820e+00 2.000e-02 2.800e-01 1.000e-02 1.000e-02 0.000e+00
  2.000e-02 4.000e-02 3.000e-02 2.920e+00 3.758e-03 1.100e-01 7.000e+00]]

In [11]:
import pickle

In [12]:
filename='Pred_Kesuburan.sav'
pickle.dump(Dc,open(filename,'wb'))